version: 2.1
orbs:
  aws-ecs: circleci/aws-ecs@6.15.3
  aws-ecr: circleci/aws-cli@2.1.0
  aws-cli: cicleci/aws-cli@2.0.0
jobs:
  tes:
    docker:
      - image: cicleci/ruby-2.6.5-node-browsers
      environment:
        RAILS_ENV: test
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_USER: root
        DB_ROOT_PASSWORD: password
      - image: circleci/mysql: 8.0.16
        command: mysqld --default-authentication-plugin=mysql_native_password
        

